In [22]:
import tensorflow
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from pandas import read_csv
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import confusion_matrix

Using TensorFlow backend.

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive

### 1. Read the dataset

In [8]:
# load dataset

bankdf = read_csv("/content/drive/My Drive/Colab Notebooks/All Data Files/bank.csv")
bankdf.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

### 2. Drop the columns which are unique for all users like IDs (5 points)

In [0]:
bankdf.drop(['CustomerId','RowNumber','Surname'], axis=1, inplace = True)

In [10]:
bankdf.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

3. Distinguish the feature and target set (5 points)

In [0]:
# split into input (X) and output (Y) variables
X = bankdf.iloc[:,0:10]
Y = bankdf.iloc[:,10]

In [12]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
dtypes: float64(2), int64(6), object(2)
memory usage: 781.3+ KB

In [13]:
X.iloc[:,2]

0       Female
1       Female
2       Female
3       Female
4       Female
5         Male
6         Male
7       Female
8         Male
9         Male
10        Male
11        Male
12      Female
13      Female
14      Female
15        Male
16        Male
17      Female
18        Male
19      Female
20        Male
21      Female
22      Female
23        Male
24      Female
25        Male
26        Male
27        Male
28      Female
29        Male
         ...
9970      Male
9971    Female
9972      Male
9973      Male
9974      Male
9975      Male
9976    Female
9977    Female
9978      Male
9979    Female
9980      Male
9981      Male
9982    Female
9983      Male
9984      Male
9985      Male
9986      Male
9987      Male
9988      Male
9989      Male
9990      Male
9991    Female
9992      Male
9993      Male
9994    Female
9995      Male
9996      Male
9997    Female
9998      Male
9999    Female
Name: Gender, Length: 10000, dtype: object

In [0]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
label_X_gender_encoder = LabelEncoder()
X.iloc[:,2] = label_X_gender_encoder.fit_transform(X.iloc[:,2])

In [0]:

label_X_country_encoder = LabelEncoder()
X.iloc[:,1] = label_X_country_encoder.fit_transform(X.iloc[:,1])

In [16]:
countryhotencoder = OneHotEncoder(categorical_features = [1]) # 1 is the country column
X = countryhotencoder.fit_transform(X).toarray()

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)

### 4. Divide the data set into Train and test sets

In [0]:
# Splitting the dataset into the Training and Testing set.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.2, random_state = 0)

### 5. Normalize the train and test data (5 points)

In [0]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### 6. Initialize & build the model (10 points)

In [23]:
# Initializing the ANN
classifier = Sequential()

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:66: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [24]:
# This adds the input layer (by specifying input dimension) AND the first hidden layer (units)
classifier.add(Dense(activation = 'relu', input_dim = 12, units=6, kernel_initializer='uniform'))

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4432: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

In [0]:
# Adding the second hidden layer
# Notice that we do not need to specify input dim. 
classifier.add(Dense(activation = 'relu', units=6, kernel_initializer='uniform'))

In [0]:
# Adding the output layer
# Notice that we do not need to specify input dim. 
# we have an output of 1 node, which is the the desired dimensions of our output (stay with the bank or not)
# We use the sigmoid because we want probability outcomes
classifier.add(Dense(activation = 'sigmoid', units=1, kernel_initializer='uniform'))

### 7. Optimize the model (Optional)

In [27]:
classifier.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:793: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3657: The name tf.log is deprecated. Please use tf.math.log instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

In [28]:
classifier.fit(X_train, y_train, batch_size=10, epochs=100)

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:1033: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.

Epoch 1/100
8000/8000 [==============================] - 2s 194us/step - loss: 0.4791 - acc: 0.7964
Epoch 2/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.4225 - acc: 0.8186
Epoch 3/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.4166 - acc: 0.8221
Epoch 4/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.4121 - acc: 0.8259
Epoch 5/100
8000/8000 [==============================] - 1s 108us/step - loss: 0.4094 - acc: 0.8315
Epoch 6/100
8000/8000 [==============================] - 1s 116us/step - loss: 0.4064 - acc: 0.8310
Epoch 7/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.4054 - acc: 0.8327
Epoch 8/100
8000/8000 [==============================] - 1s 108us/step - loss: 0.4041 - acc: 0.8331
Epoch 9/100
8000/8000 [==============================] - 1s 112us/step - loss: 0.4036 - acc: 0.8334
Epoch 10/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.4025 - acc: 0.8336
Epoch 11/100
8000/8000 [==============================] - 1s 109us/step - loss: 0.4018 - acc: 0.8335
Epoch 12/100
8000/8000 [==============================] - 1s 112us/step - loss: 0.4011 - acc: 0.8339
Epoch 13/100
8000/8000 [==============================] - 1s 109us/step - loss: 0.4007 - acc: 0.8344
Epoch 14/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.4004 - acc: 0.8347
Epoch 15/100
8000/8000 [==============================] - 1s 109us/step - loss: 0.4002 - acc: 0.8351
Epoch 16/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.3990 - acc: 0.8344
Epoch 17/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.3991 - acc: 0.8350
Epoch 18/100
8000/8000 [==============================] - 1s 108us/step - loss: 0.3983 - acc: 0.8365
Epoch 19/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.3976 - acc: 0.8351
Epoch 20/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.3969 - acc: 0.8376
Epoch 21/100
8000/8000 [==============================] - 1s 109us/step - loss: 0.3959 - acc: 0.8380
Epoch 22/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.3958 - acc: 0.8372
Epoch 23/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.3952 - acc: 0.8365
Epoch 24/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.3946 - acc: 0.8372
Epoch 25/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.3949 - acc: 0.8387
Epoch 26/100
8000/8000 [==============================] - 1s 118us/step - loss: 0.3943 - acc: 0.8392
Epoch 27/100
8000/8000 [==============================] - 1s 109us/step - loss: 0.3941 - acc: 0.8377
Epoch 28/100
8000/8000 [==============================] - 1s 109us/step - loss: 0.3931 - acc: 0.8402
Epoch 29/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.3915 - acc: 0.8396
Epoch 30/100
8000/8000 [==============================] - 1s 108us/step - loss: 0.3899 - acc: 0.8381
Epoch 31/100
8000/8000 [==============================] - 1s 105us/step - loss: 0.3862 - acc: 0.8380
Epoch 32/100
8000/8000 [==============================] - 1s 108us/step - loss: 0.3839 - acc: 0.8401
Epoch 33/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.3815 - acc: 0.8385
Epoch 34/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.3787 - acc: 0.8394
Epoch 35/100
8000/8000 [==============================] - 1s 109us/step - loss: 0.3761 - acc: 0.8390
Epoch 36/100
8000/8000 [==============================] - 1s 109us/step - loss: 0.3751 - acc: 0.8407
Epoch 37/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.3731 - acc: 0.8420
Epoch 38/100
8000/8000 [==============================] - 1s 109us/step - loss: 0.3714 - acc: 0.8420
Epoch 39/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.3704 - acc: 0.8439
Epoch 40/100
8000/8000 [==============================] - 1s 117us/step - loss: 0.3694 - acc: 0.8447
Epoch 41/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.3671 - acc: 0.8451
Epoch 42/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.3664 - acc: 0.8479
Epoch 43/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.3646 - acc: 0.8474
Epoch 44/100
8000/8000 [==============================] - 1s 114us/step - loss: 0.3643 - acc: 0.8469
Epoch 45/100
8000/8000 [==============================] - 1s 113us/step - loss: 0.3641 - acc: 0.8472
Epoch 46/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.3630 - acc: 0.8492
Epoch 47/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.3623 - acc: 0.8480
Epoch 48/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.3620 - acc: 0.8484
Epoch 49/100
8000/8000 [==============================] - 1s 109us/step - loss: 0.3616 - acc: 0.8481
Epoch 50/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.3604 - acc: 0.8514
Epoch 51/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.3595 - acc: 0.8476
Epoch 52/100
8000/8000 [==============================] - 1s 115us/step - loss: 0.3586 - acc: 0.8489
Epoch 53/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.3572 - acc: 0.8529
Epoch 54/100
8000/8000 [==============================] - 1s 109us/step - loss: 0.3559 - acc: 0.8516
Epoch 55/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.3538 - acc: 0.8524
Epoch 56/100
8000/8000 [==============================] - 1s 112us/step - loss: 0.3531 - acc: 0.8544
Epoch 57/100
8000/8000 [==============================] - 1s 112us/step - loss: 0.3510 - acc: 0.8556
Epoch 58/100
8000/8000 [==============================] - 1s 109us/step - loss: 0.3499 - acc: 0.8560
Epoch 59/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.3491 - acc: 0.8560
Epoch 60/100
8000/8000 [==============================] - 1s 109us/step - loss: 0.3482 - acc: 0.8560
Epoch 61/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.3476 - acc: 0.8579
Epoch 62/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.3478 - acc: 0.8564
Epoch 63/100
8000/8000 [==============================] - 1s 114us/step - loss: 0.3454 - acc: 0.8584
Epoch 64/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.3455 - acc: 0.8574
Epoch 65/100
8000/8000 [==============================] - 1s 117us/step - loss: 0.3444 - acc: 0.8592
Epoch 66/100
8000/8000 [==============================] - 1s 114us/step - loss: 0.3435 - acc: 0.8571
Epoch 67/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.3431 - acc: 0.8576
Epoch 68/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.3418 - acc: 0.8586
Epoch 69/100
8000/8000 [==============================] - 1s 113us/step - loss: 0.3423 - acc: 0.8582
Epoch 70/100
8000/8000 [==============================] - 1s 116us/step - loss: 0.3415 - acc: 0.8607
Epoch 71/100
8000/8000 [==============================] - 1s 108us/step - loss: 0.3412 - acc: 0.8610
Epoch 72/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.3397 - acc: 0.8609
Epoch 73/100
8000/8000 [==============================] - 1s 109us/step - loss: 0.3406 - acc: 0.8577
Epoch 74/100
8000/8000 [==============================] - 1s 112us/step - loss: 0.3396 - acc: 0.8574
Epoch 75/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.3402 - acc: 0.8597
Epoch 76/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.3401 - acc: 0.8612
Epoch 77/100
8000/8000 [==============================] - 1s 109us/step - loss: 0.3399 - acc: 0.8604
Epoch 78/100
8000/8000 [==============================] - 1s 113us/step - loss: 0.3396 - acc: 0.8592
Epoch 79/100
8000/8000 [==============================] - 1s 108us/step - loss: 0.3391 - acc: 0.8607
Epoch 80/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.3383 - acc: 0.8612
Epoch 81/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.3387 - acc: 0.8612
Epoch 82/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.3390 - acc: 0.8605
Epoch 83/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.3392 - acc: 0.8597
Epoch 84/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.3386 - acc: 0.8617
Epoch 85/100
8000/8000 [==============================] - 1s 113us/step - loss: 0.3376 - acc: 0.8605
Epoch 86/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.3387 - acc: 0.8606
Epoch 87/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.3380 - acc: 0.8612
Epoch 88/100
8000/8000 [==============================] - 1s 108us/step - loss: 0.3379 - acc: 0.8604
Epoch 89/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.3385 - acc: 0.8599
Epoch 90/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.3375 - acc: 0.8607
Epoch 91/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.3386 - acc: 0.8606
Epoch 92/100
8000/8000 [==============================] - 1s 113us/step - loss: 0.3382 - acc: 0.8595
Epoch 93/100
8000/8000 [==============================] - 1s 112us/step - loss: 0.3380 - acc: 0.8600
Epoch 94/100
8000/8000 [==============================] - 1s 113us/step - loss: 0.3381 - acc: 0.8621
Epoch 95/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.3377 - acc: 0.8605
Epoch 96/100
8000/8000 [==============================] - 1s 109us/step - loss: 0.3371 - acc: 0.8604
Epoch 97/100
8000/8000 [==============================] - 1s 108us/step - loss: 0.3373 - acc: 0.8629
Epoch 98/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.3380 - acc: 0.8596
Epoch 99/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.3365 - acc: 0.8629
Epoch 100/100
8000/8000 [==============================] - 1s 108us/step - loss: 0.3370 - acc: 0.8609

### 8. Predict the results using 0.5 as a threshold (Optional)

In [29]:
y_pred = classifier.predict_classes(X_test)
print(y_pred)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]

### 2. Print the Accuracy score and confusion matrix (5 points)

In [30]:

cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1501   94]
 [ 183  222]]

In [31]:
X_test.shape

(2000, 12)

In [32]:
classifier.evaluate(X_test,y_test)

2000/2000 [==============================] - 0s 36us/step

[0.33508820784091947, 0.8615]

Model accuracy 84.2%